name = "StaticThreadSchedules"
uuid = "f8dcff43-85b6-488e-a967-a0bbd70265e4"
authors = ["Zack Li"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
